// <auto-generated />
namespace DalMySQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Init1309 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Init1309));
        
        string IMigrationMetadata.Id
        {
            get { return "201809131535000_Init 13.09"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
