// <auto-generated />
namespace DalMySQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class noIdea : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(noIdea));
        
        string IMigrationMetadata.Id
        {
            get { return "202006271310225_no Idea"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
